version: '3.1'
services:
  server:
    build: .
    container_name: server
    environment:
      NODE_ENV : production
      MY_DataBase_URI: mongodb://mongodb:27017/MyDataBase
      SESSION_SECRET: donttellanyone
      PORT: 3001
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../data:/data/db
  
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config